mod login;

pub use self::login::Login;
pub use pokemmo_macros::codec;

/// The `Codec` trait defines serialization and deserialization for protocol messages.
///
/// Implementations of this trait are typically generated by the `#[codec]` procedural macro,
/// which creates enum variants that map to specific opcodes and message types.
///
/// ## Examples
///
/// ```ignore
/// use pokemmo::codec::Codec;
///
/// let msg = Login::ClientHello(client_hello);
/// let encoded = msg.encode()?;
/// let decoded = Login::decode(&encoded)?;
/// ```
pub trait Codec {
    /// Encodes this codec variant into a byte vector.
    ///
    /// The encoded format is: `[opcode, payload...]` where the opcode is the
    /// first byte and the payload is the serialized message data.
    ///
    /// ## Errors
    ///
    /// Returns an error if serialization of the message fails.
    fn encode(&self) -> std::io::Result<Vec<u8>>;

    /// Decodes a byte slice into a codec variant.
    ///
    /// Reads the first byte as the opcode and uses it to determine which variant
    /// to instantiate. The remaining bytes are deserialized as the message payload.
    ///
    /// ## Errors
    ///
    /// Returns an error if:
    /// - The data is empty (no opcode byte).
    /// - The opcode is unknown and no `Unknown` variant is defined.
    /// - Deserialization of the message payload fails.
    fn decode(data: &[u8]) -> std::io::Result<Self>
    where
        Self: Sized;
}
